controller_list:
  - name: /crane_x7/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - crane_x7_shoulder_fixed_part_pan_joint
      - crane_x7_shoulder_revolute_part_tilt_joint
      - crane_x7_upper_arm_revolute_part_twist_joint
      - crane_x7_upper_arm_revolute_part_rotate_joint
      - crane_x7_lower_arm_fixed_part_joint
      - crane_x7_lower_arm_revolute_part_joint
      - crane_x7_wrist_joint
  - name: /crane_x7/gripper_controller
    action_ns: gripper_cmd
    type: GripperCommand
    default: true
    joints:
      - crane_x7_gripper_finger_a_joint

